### ISSUE TITLE
[Issue]: Bank Informaiton not syncing to Production

### ISSUE THREAD

**Issue by pradeep-agnihotri** [paypal/mirakl-hyperwallet-connector#103]
### Describe the Issue

This is a follow up to the closed ticket - [101](https://github.com/paypal/mirakl-hyperwallet-connector/issues/101).

During the sync process the Bank Account information is not getting synced to the HyperWallet Account. Attached are the logs that provide more detailed logs.
[hwc_logs_20221107-03.txt](https://github.com/paypal/mirakl-hyperwallet-connector/files/9961621/hwc_logs_20221107-03.txt)

In the logs we can observe a warning;
No bank account info for shop code: [2000]

We have validated the following fields have been setup for the bank account information;
1. Bank account owner name
2. Bank name
3. Bank address
4. Bank Zip Code/Postal code
5. Bank City/Town
6. Bank Account State/Province
7. Bank Account Number
8. Routing Number (ABA)
9. BIC

### Environment

Live/Production

### Version

4.14.0

### Expected Behavior

1. The bank account information should get sync into HyperWallet.
2. The Bank account HyperWallet Token should get updated back in Mirakl.

### Actual Behavior

1. The Sellers Bank account is not created in HyperWallet and subsequently there is no Bank Account token generated.

### Steps to Reproduce

1. Create a new Seller account in Mirakl as Professional.
2. Sync Seller account to HyperWallet via the HW Connector App "Professional Seller" sync.
3. Add bank account information to the Seller in Mirakl.
4. Run the Bank Account Sync via the HW Connector App.
5. Observe that the sync process runs, but Bank account is not updated in Mirakl.

### Relevant log output

```shell
2022-11-07 22:08:44.891 INFO .p.i.j.l.JobExecutionInformationListener : Finished [bankAccountExtractJob] at 2022-11-07T22:08:44.891304327
2022-11-07 22:08:44.890 WARN s.HyperWalletBankAccountStrategyExecutor : No bank account info for shop code: [2000]
2022-11-07 22:08:44.890 INFO .l.LoggingBatchJobItemProcessingListener : [BankAccountExtractBatchJob] Processed successfully item of type BankAccount with id: 2000
2022-11-07 22:08:44.890 INFO .l.LoggingBatchJobItemProcessingListener : [BankAccountExtractBatchJob] 1 items processed successfully. 0 items failed. 0 items remaining
2022-11-07 22:08:44.889 INFO .l.LoggingBatchJobItemProcessingListener : [BankAccountExtractBatchJob] Retrieved the following number of items to be processed: 1
2022-11-07 22:08:44.889 INFO .l.LoggingBatchJobItemProcessingListener : [BankAccountExtractBatchJob] Processing item of type BankAccount with id: 2000
2022-11-07 22:08:44.888 WARN b.c.i.m.MiraklToBankAccountModelExecutor : No bank account info for shop code: [2000]
2022-11-07 22:08:44.887 INFO .s.s.s.i.MiraklSellersExtractServiceImpl : Shops retrieved [2000]
2022-11-07 22:08:44.782 INFO .s.s.s.i.MiraklSellersExtractServiceImpl : Shops retrieved []
2022-11-07 22:08:44.782 INFO .s.s.s.i.MiraklSellersExtractServiceImpl : Retrieving shops since Mon Nov 07 22:05:44 UTC 2022
2022-11-07 22:08:44.684 INFO .l.LoggingBatchJobItemProcessingListener : [BankAccountExtractBatchJob] Starting extraction of items to be processed
2022-11-07 22:08:44.684 INFO .s.s.s.i.MiraklSellersExtractServiceImpl : Retrieving shops since Mon Nov 07 22:05:44 UTC 2022
2022-11-07 22:08:44.681 INFO .p.i.j.l.JobExecutionInformationListener : Started [bankAccountExtractJob] at 2022-11-07T22:08:44.681145179
```

**Comment by pradeep-agnihotri** [comment]
@max6001 , @kshunt-paypal the issue has been created as requested.

**Comment by quim3ra** [comment]
HI @pradeep-agnihotri,

Could you please enable the log to debug level for the package `com.paypal.sellers.bankaccountextract.service.impl` and re-run the `bankAccountExtractJob` this way we would have more information to asses the issue.

To do so in a live environment you can query the connector this way (replacing `your_env` by the actual address of the connector

```
curl 'http://your_env/actuator/loggers/com.paypal.sellers.bankaccountextract.service.impl' -i -X POST \
    -H 'Content-Type: application/json' \
    -d '{"configuredLevel":"debug"}'
```

**Comment by pradeep-agnihotri** [comment]
Hello @quim3ra 
We are making these updates to the production and once more logs are generated will share here.

**Comment by pradeep-agnihotri** [comment]
Hello @quim3ra , @max6001 
Any update on the above comment?

**Comment by quim3ra** [comment]
Hi @pradeep-agnihotri ,

Please add the property `management.endpoints.web.exposure.include=loggers` to the file: `web/src/main/resources/application.properties` and restart the connector. Afterwards you can proceed with the procedure described here https://github.com/paypal/mirakl-hyperwallet-connector/issues/103#issuecomment-1308742376

**Comment by pradeep-agnihotri** [comment]
Hello @quim3ra 
We had published the changes to the production, however we were getting 503 error when trying to access the "/actuator/health" endpoint; below is the error;
`<body text=#000000 bgcolor=#ffffff>
    <h1>Error: Server Error</h1>
    <h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.
    </h2>
    <h2></h2>
</body>`

To troubleshoot and match the other already existing entries in the "application.properties" file we update the provided line to be as below; notice that the "s" has been removed from "endpoints". This time the endpoint gave no error but the loggers were still not active.
`management.endpoint.web.exposure.include          = loggers`

After this change we still got 404 when tried updating the logger level;
`curl 'http://your_env/actuator/loggers/com.paypal.sellers.bankaccountextract.service.impl' -i -X POST \
    -H 'Content-Type: application/json' \
    -d '{"configuredLevel":"debug"}'`

**response**;
`{
    "timestamp": 1669135288935,
    "status": 404,
    "error": "Not Found",
    "path": "/actuator/loggers/com.paypal.sellers.bankaccountextract.service.impl"
}`


Can you please confirm if the "endpoints" should be with "s" or without?
Any other way to follow to update the logger level?

Thanks.

**Comment by quim3ra** [comment]
> Hello @quim3ra We had published the changes to the production, however we were getting 503 error when trying to access the "/actuator/health" endpoint; below is the error; `
> 
> # Error: Server Error
> 
> ## The server encountered a temporary error and could not complete your request.
> Please try again in 30 seconds.
> 
> 
> `
> To troubleshoot and match the other already existing entries in the "application.properties" file we update the provided line to be as below; notice that the "s" has been removed from "endpoints". This time the endpoint gave no error but the loggers were still not active. `management.endpoint.web.exposure.include = loggers`
> 
> After this change we still got 404 when tried updating the logger level; `curl 'http://your_env/actuator/loggers/com.paypal.sellers.bankaccountextract.service.impl' -i -X POST \ -H 'Content-Type: application/json' \ -d '{"configuredLevel":"debug"}'`
> 
> **response**; `{ "timestamp": 1669135288935, "status": 404, "error": "Not Found", "path": "/actuator/loggers/com.paypal.sellers.bankaccountextract.service.impl" }`
> 
> Can you please confirm if the "endpoints" should be with "s" or without? Any other way to follow to update the logger level?
> 
> Thanks.

Hi, the error you are describing does not look like an error that comes from the connector application. Anyway, the property that should be set is the one described in the comment https://github.com/paypal/mirakl-hyperwallet-connector/issues/103#issuecomment-1315015125, not the one without `s` as described in official Spring Documentation: 

Anyway, instead of setting the DEBUG level to that package dynamically via the actuator endpoint, we can achieve the same by setting it via properties in the `application.properties` file by adding this line:

`logging.level.com.paypal.sellers.bankaccountextract.service.impl=DEBUG`

After adding this line, you need to restart the connector and re-run the `bankAccountExtractJob`

**Comment by pradeep-agnihotri** [comment]
On enabling the debug code via code worked. 
`logging.level.com.paypal.sellers.bankaccountextract.service.impl=DEBUG

The logs pointed to the missing payment_info node in the response, hence closing the ticket.
