### ISSUE TITLE
[Issue]: Professional Seller Extract Job not updating First name and Last Name

### ISSUE THREAD

**Issue by Msolia1** [paypal/mirakl-hyperwallet-connector#106]
### Describe the Issue

Hello,

Using Professional Seller Extract Job, We are having below issues,

1) We are unable to retrieve Firstname and LastName while creating Professional Sellers in Hyperwallet.
2) We are unable to update data for existing released distributor ID and email in Hyperwallet.

We don't see any errors in logs as well.

Attached screenshots below,

Issue 1) Below Screenshot

![image](https://user-images.githubusercontent.com/114497129/205236647-1ecdba25-328d-4a3b-b9de-1ab00f573ad6.png)

Issue 2) Below Screenshot
![image](https://user-images.githubusercontent.com/114497129/205237263-cdd551e1-5423-48e5-9387-4941af3f78a5.png)

----------------------------------------------------------------------------------------------------------------------------------------
Logs
01-12-2022 10:06:11.788 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"314baf08-9a9b-43c1-8d6a-fd7555da606f","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Updating token for shop [2010] to [usr-f52d8905-f35c-4d59-9316-085113089dee]
01-12-2022 10:06:13.752 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"314baf08-9a9b-43c1-8d6a-fd7555da606f","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.sellers.sellersextract.service.strategies.HyperWalletUpdateSellerServiceStrategy - Seller updated for seller with clientUserId [2010]
01-12-2022 10:06:13.754 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"314baf08-9a9b-43c1-8d6a-fd7555da606f","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processed successfully item of type ProfessionalSeller with id: 2010
01-12-2022 10:06:13.755 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"314baf08-9a9b-43c1-8d6a-fd7555da606f","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - 1 items processed successfully. 0 items failed. 0 items remaining
01-12-2022 10:06:13.758 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"314baf08-9a9b-43c1-8d6a-fd7555da606f","subtype":"ProfessionalSellersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Finished processing of job
01-12-2022 10:06:13.775 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"471a2a4f-2e1d-47a0-9f70-f459c05e7970","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting processing of job
01-12-2022 10:06:13.776 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"471a2a4f-2e1d-47a0-9f70-f459c05e7970","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting extraction of items to be processed
01-12-2022 10:06:13.776 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"471a2a4f-2e1d-47a0-9f70-f459c05e7970","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Thu Dec 01 09:06:09 UTC 2022
01-12-2022 10:06:13.938 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"471a2a4f-2e1d-47a0-9f70-f459c05e7970","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved [2010]
01-12-2022 10:06:13.940 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"471a2a4f-2e1d-47a0-9f70-f459c05e7970","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Retrieved the following number of items to be processed: 0
01-12-2022 10:06:13.942 [HyperwalletMiraklScheduler_Worker-9] INFO  {"id":"471a2a4f-2e1d-47a0-9f70-f459c05e7970","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Finished processing of job
01-12-2022 10:06:13.942 [HyperwalletMiraklScheduler_Worker-9] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Finished [professionalSellersExtractJob] at 2022-12-01T10:06:13.942839888
01-12-2022 10:09:16.761 [HyperwalletMiraklScheduler_Worker-2] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Started [invoicesExtractJob] at 2022-12-01T10:09:16.761916106
01-12-2022 10:09:16.762 [HyperwalletMiraklScheduler_Worker-2] INFO   com.paypal.invoices.jobs.InvoicesExtractJob - Payment of commissions is enabled, retrieving payments for the operator
01-12-2022 10:09:16.770 [HyperwalletMiraklScheduler_Worker-2] INFO  {"id":"f4f4aef3-55c7-43c1-8aa1-668d9b5fdd92","subtype":"InvoicesExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting processing of job
01-12-2022 10:09:16.772 [HyperwalletMiraklScheduler_Worker-2] INFO  {"id":"f4f4aef3-55c7-43c1-8aa1-668d9b5fdd92","subtype":"InvoicesExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting extraction of items to be processed
01-12-2022 10:09:16.950 [HyperwalletMiraklScheduler_Worker-2] INFO  {"id":"f4f4aef3-55c7-43c1-8aa1-668d9b5fdd92","subtype":"InvoicesExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Retrieved the following number of items to be processed: 0
01-12-2022 10:09:16.951 [HyperwalletMiraklScheduler_Worker-2] INFO  {"id":"f4f4aef3-55c7-43c1-8aa1-668d9b5fdd92","subtype":"InvoicesExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Finished processing of job
01-12-2022 10:09:16.953 [HyperwalletMiraklScheduler_Worker-2] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Finished [invoicesExtractJob] at 2022-12-01T10:09:16.953043306
01-12-2022 10:10:04.232 [HyperwalletMiraklScheduler_Worker-3] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Started [bankAccountExtractJob] at 2022-12-01T10:10:04.232229936
01-12-2022 10:10:04.235 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting processing of job
01-12-2022 10:10:04.236 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting extraction of items to be processed
01-12-2022 10:10:04.247 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Thu Dec 01 09:10:04 UTC 2022
01-12-2022 10:10:04.513 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved []
01-12-2022 10:10:04.514 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Thu Dec 01 09:10:04 UTC 2022
01-12-2022 10:10:04.690 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved [2010]
01-12-2022 10:10:04.695 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Retrieved the following number of items to be processed: 1
01-12-2022 10:10:04.705 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processing item of type BankAccount with id: 2010
01-12-2022 10:10:05.763 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.sellers.bankaccountextract.service.impl.MiraklBankAccountExtractServiceImpl - Updating bank account token for shop [2010]
01-12-2022 10:10:06.336 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.sellers.bankaccountextract.service.impl.MiraklBankAccountExtractServiceImpl - Bank account token updated for shop [2010]
01-12-2022 10:10:08.150 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.sellers.bankaccountextract.service.strategies.AbstractHyperwalletBankAccountRetryApiStrategy - Bank account created or updated for seller with clientId [2010]
01-12-2022 10:10:08.152 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processed successfully item of type BankAccount with id: 2010
01-12-2022 10:10:08.152 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - 1 items processed successfully. 0 items failed. 0 items remaining
01-12-2022 10:10:08.153 [HyperwalletMiraklScheduler_Worker-3] INFO  {"id":"21cfdb5f-59f4-4d58-a9dd-ef0145bc2296","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Finished processing of job
01-12-2022 10:10:08.154 [HyperwalletMiraklScheduler_Worker-3] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Finished [bankAccountExtractJob] at 2022-12-01T10:10:08.154043734
01-12-2022 10:13:21.429 [HyperwalletMiraklScheduler_Worker-8] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Started [professionalSellersExtractJob] at 2022-12-01T10:13:21.429890013
01-12-2022 10:13:21.442 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting processing of job
01-12-2022 10:13:21.442 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting extraction of items to be processed
01-12-2022 10:13:21.442 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Thu Dec 01 09:13:20 UTC 2022
01-12-2022 10:13:21.652 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved [2010,2004]
01-12-2022 10:13:21.657 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Retrieved the following number of items to be processed: 2
01-12-2022 10:13:21.659 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processing item of type ProfessionalSeller with id: 2010
01-12-2022 10:13:23.918 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.sellers.sellersextract.service.strategies.HyperWalletUpdateSellerServiceStrategy - Seller updated for seller with clientUserId [2010]
01-12-2022 10:13:23.920 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processed successfully item of type ProfessionalSeller with id: 2010
01-12-2022 10:13:23.921 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - 1 items processed successfully. 0 items failed. 1 items remaining
01-12-2022 10:13:23.923 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2004","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processing item of type ProfessionalSeller with id: 2004
01-12-2022 10:13:24.485 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2004","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Updating token for shop [2004] to [usr-da2a3ca4-a3d9-43ce-bf7e-f9fc070524de]
01-12-2022 10:13:24.703 [HyperwalletMiraklScheduler_Worker-4] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Started [bankAccountExtractJob] at 2022-12-01T10:13:24.703295718
01-12-2022 10:13:24.708 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting processing of job
01-12-2022 10:13:24.708 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting extraction of items to be processed
01-12-2022 10:13:24.709 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Thu Dec 01 09:13:24 UTC 2022
01-12-2022 10:13:25.265 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved []
01-12-2022 10:13:25.265 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Thu Dec 01 09:13:24 UTC 2022
01-12-2022 10:13:25.426 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved [2010,2004]
01-12-2022 10:13:25.452 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Retrieved the following number of items to be processed: 2
01-12-2022 10:13:25.454 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processing item of type BankAccount with id: 2010
01-12-2022 10:13:25.867 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2004","type":"BatchJob"} com.paypal.sellers.sellersextract.service.strategies.HyperWalletUpdateSellerServiceStrategy - Seller updated for seller with clientUserId [2004]
01-12-2022 10:13:25.869 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2004","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processed successfully item of type ProfessionalSeller with id: 2004
01-12-2022 10:13:25.870 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","itemType":"ProfessionalSeller","itemId":"2004","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - 2 items processed successfully. 0 items failed. 0 items remaining
01-12-2022 10:13:25.874 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"e215f431-5c4f-428c-9549-d0a0a44bbf70","subtype":"ProfessionalSellersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Finished processing of job
01-12-2022 10:13:25.878 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"3730937c-0ba8-4f48-925e-14fec3c5b87d","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting processing of job
01-12-2022 10:13:25.878 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"3730937c-0ba8-4f48-925e-14fec3c5b87d","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting extraction of items to be processed
01-12-2022 10:13:25.878 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"3730937c-0ba8-4f48-925e-14fec3c5b87d","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Thu Dec 01 09:13:20 UTC 2022
01-12-2022 10:13:26.027 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"3730937c-0ba8-4f48-925e-14fec3c5b87d","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved [2010,2004]
01-12-2022 10:13:26.036 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"3730937c-0ba8-4f48-925e-14fec3c5b87d","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Retrieved the following number of items to be processed: 0
01-12-2022 10:13:26.038 [HyperwalletMiraklScheduler_Worker-8] INFO  {"id":"3730937c-0ba8-4f48-925e-14fec3c5b87d","subtype":"BusinessStakeholdersExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Finished processing of job
01-12-2022 10:13:26.038 [HyperwalletMiraklScheduler_Worker-8] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Finished [professionalSellersExtractJob] at 2022-12-01T10:13:26.038189281
01-12-2022 10:13:27.112 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.sellers.bankaccountextract.service.strategies.AbstractHyperwalletBankAccountRetryApiStrategy - Bank account created or updated for seller with clientId [2010]
01-12-2022 10:13:27.114 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processed successfully item of type BankAccount with id: 2010
01-12-2022 10:13:27.115 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2010","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - 1 items processed successfully. 0 items failed. 1 items remaining
01-12-2022 10:13:27.117 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2004","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processing item of type BankAccount with id: 2004
01-12-2022 10:13:27.939 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2004","type":"BatchJob"} com.paypal.sellers.bankaccountextract.service.impl.MiraklBankAccountExtractServiceImpl - Updating bank account token for shop [2004]
01-12-2022 10:13:28.347 [HyperwalletMiraklScheduler_Worker-4] INFO  {"id":"a70a775e-b8e5-404a-b6ff-791bd86af8ca","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2004","type":"BatchJob"} com.paypal.sellers.bankaccountextract.service.impl.MiraklBankAccountExtractServiceImpl - Bank account token updated for shop [2004]
----------------------------------------------------------------------------------------------------------------------------------------

Thanks,
Madhav

### Environment

Test/UAT

### Version

4.17.0

**Comment by Msolia1** [comment]
could we please get response on this issue?

**Comment by javierpoloe2y** [comment]
Hi @Msolia1,

First name and last name are only updated for non-professional shops. So only the Individual Sellers Extract Job, which processes non-professional shops, will update those fields.

The `Distributor ID` corresponds to the ID of the shop in Mirakl, which is something that can't be changed once the shop is created. Looking at the logs you have provided we have found that:

- `User Token` for shop `2004` is `usr-da2a3ca4-a3d9-43ce-bf7e-f9fc070524de`.
- `User Token` for shop `2010` is `usr-f52d8905-f35c-4d59-9316-085113089dee`.

According to this the information shown in the second screenshot corresponds to shop `2004`, and the distributor ID and user token is consistent with what we see in the logs. So we don't see any problem with the distributor ID.

And finally regarding the email address, as you said we don't see any problem in the logs. You can try to make any change in the shop in Mirakl, and rerun again the professional sellers extract job to see If the mail is correctly updated.

**Comment by Msolia1** [comment]
Thanks for your reply,

For issue 1) We have created new user in Hyperwallet, For which First name and Last name is showing blank.

For issue 2) We made the user non-professional and tried to updated the details like first name and last name, but still data is not getting updated.

**Comment by javierpoloe2y** [comment]
Hi @Msolia1,

Could you provide a screenshot of Hyperwallet account list result and account details page for an individual and a professional seller to better understand what is happening? (similar to the ones in the first post).

**Comment by Msolia1** [comment]
Hello @javierpoloe2y ,

![image](https://user-images.githubusercontent.com/114497129/206490617-492d13b6-7edc-49cc-8f3e-1a4c55d8c303.png)

![image](https://user-images.githubusercontent.com/114497129/206491291-eaa59038-a3fc-4867-b9f7-5c67d42d7ff2.png)


In first screenshot, For distributor ID 2010 first and last name is blank, 
In second screenshot, We have added first and last name in Mirakl for this shop 2010.

Thanks,
Madhav

**Comment by javierpoloe2y** [comment]
Hi @Msolia1,

I see from the screenshot that your distributor 2010 is a professional seller. In that case, only the shop name is sent to Hyperwallet, and not the first and last name.

First and last name are sent to Hyperwallet only for individual sellers.

**Comment by javierpoloe2y** [comment]
Hi @Msolia1,

We are closing this issue since there hasn`t been activity for a pair of weeks. Don't hesitate to reopen it if you need more information.
