### ISSUE TITLE
[Issue]: Invoices Extract Job not working fine

### ISSUE THREAD

**Issue by Msolia1** [paypal/mirakl-hyperwallet-connector#107]
### Describe the Issue

Hi,

InvoicesExtractJob is not working fine, We don't see any transaction have been created in Hyperwallet from Mirakl.

Though it says in logs “Invoice 230198 already sent to Hyperwallet” we don’t see any transaction history in Hyperwallet.

Below are logs from HMC,

![image](https://user-images.githubusercontent.com/114497129/208430419-8d56fc70-a2e8-4aa3-97e8-53b6856e57e8.png)

![image](https://user-images.githubusercontent.com/114497129/208430497-81e1180a-4488-4613-851e-adb4d776632a.png)

Could you please check and let us know how to resolve this issue.

Thanks,
Madhav

### Environment

Test/UAT

### Version

4.17.0

**Comment by Msolia1** [comment]
Hi,

Could we get update on this please,

We checked with PayPal team, They mentioned "Thank you for sharing the screenshot, I can see that /job/invoices-extract?name=invoiceExtractJob is POST but we are getting the GET call on these invoice ids: 230199, 230198."

![image](https://user-images.githubusercontent.com/114497129/208599736-9c768a8f-10b1-4f87-afbb-d5f578b2e31e.png)

Thanks,
Madhav

**Comment by quim3ra** [comment]
Hi @Msolia1 ,

Could you go to Search Payments under Account when you log in and search in the box that corresponds with the field `Client Payment Id / Reference #` for both 230199 and 230198 invoices and check also if there is any result over there?

You can check in this screenshot where to find the section and field.


<img width="482" alt="payment_search_box" src="https://user-images.githubusercontent.com/47243420/208636019-a3c44397-639c-4060-a595-ab39f6d7708f.png">

**Comment by Msolia1** [comment]
Hi @quim3ra ,

Thank you so much for your reply,

Looks like 230198 and 230199 Document ID have been already processed. As we have connected HW UAT environment first with Mirakl instance 1 and now connected same HW UAT environment with Mirakl instance 2.

Just want to check one thing, As shown in below screenshot, why Status shows "PENDING_ID_VERIFICATION"? How we can verify it?


![image](https://user-images.githubusercontent.com/114497129/208918866-63f414e6-7032-4229-b2b9-675954c49af4.png)

Thanks,
Madhav

**Comment by quim3ra** [comment]
HI @Msolia1,

That means that the seller whose payment is trying to be processed is pending payee verification https://docs.hyperwallet.com/content/payee-requirements/v1/payee-verification. You can check with Hyperwallet team the steps you must follow to verify sellers.

Regards,
Carlos B.
