### ISSUE TITLE
[Issue]: Incorrect Transaction Observation in Hyperwallet

### ISSUE THREAD

**Issue by Msolia1** [paypal/mirakl-hyperwallet-connector#108]
### Describe the Issue

Hi Team,

We have seen incorrect Transaction in Hyperwallet while we testing end to end flow.

In Mirakl, Payout file have been generated with document ID No. **000000230277** belongs to Store **PaiPayoutStore**, As shown below.

![image](https://user-images.githubusercontent.com/114497129/209653285-396d16ad-135d-46a9-b175-ee8624bd7080.png)

![image](https://user-images.githubusercontent.com/114497129/209653603-c165ddcf-6b26-4f88-9a9b-c129c0c329e9.png)

Now, In Hyperwallet, Seller amount for this transaction have been paid to another Seller (Payment to Sabita Stag Store).

![image-20221227-062038](https://user-images.githubusercontent.com/114497129/209653857-c5b43522-8d3c-4717-84fc-82652315ae81.png)

![Capture33333](https://user-images.githubusercontent.com/114497129/209653871-85e41e2e-b867-4bf1-9d67-102cdddc7773.JPG)

For your information we forgot to create seller account for PaiPayoutStore in Hyperwallet and ran Invoices extract job.

If this is the case, then it should not process invoices for this seller PaiPayoutStore right? As the account and bank details have been not created in Hyperwallet. Also, Invoice ID(000000230277) belong to PaiPayoutStore processed to another Seller.

Thanks,
Madhav

### Environment

Test/UAT

### Version

4.17.0

**Comment by javierpoloe2y** [comment]
Hi @Msolia1,

The connector retrieves all the invoices in `Pending` state and then creates Hyperwallet payments based on the user and bank account token associated with the invoice shop. If the seller wasn't created previously in Hyperwallet, then it's not going to have a user and bank account token in Mirakl and the invoice will be ignored.

So if a payment was created in Hyperwallet, the associated Mirakl shop should have a user and bank account token filled.

Please could you take a look at the custom fields in Mirakl for `Sabita Stag Store` and `PaiPayoutStore` and see what user token and the bank account token they have?

**Comment by javierpoloe2y** [comment]
Hi @Msolia1,

We didn't have any news about this issue for some time now, so we are going to close it. Feel free to reopen it if your problems persist.
