### ISSUE TITLE
US Bank ABA not synching

### ISSUE THREAD

**Issue by guillauc** [paypal/mirakl-hyperwallet-connector#112]
Hi,

We have our Mirakl environnement setup in CAD currency.

Some sellers are US sellers and have US Bank accounts. The connector fails to create the Bank account and giving the following message: 

"code" : "EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED",
"message" : "The bank account information provided is not configured for your program."

We found out that it's trying to add the Bank Account with: 
   "transferMethodCountry": "US",
   "transferMethodCurrency": "CAD",

That doesn't work on the Hyperwallet side.

Is there a way to create those bank accounts automatically?

Thanks,

@guillauc

**Comment by javierpoloe2y** [comment]
Hi @guillauc,

We are currently investigating this scenario with the help of the Hyperwallet team. We will come back to you soon.

**Comment by max6001** [comment]
Hi @guillauc 

Sorry for the delay.
When creating a bank account within HW, the connector is pulling:
- the transferMethodCountry from the bank account type selected (if it's IBAN, it pulls it from the first 2 letters of the IBAN)
- the transferMethodCurrency from the Mirakl Shop currency

It seems that right now you have sellers with a shop currency set to CAD but trying to add a US bank account which is not something supported by HW.

One possibility would be to modify the connector behaviour to automatically set the transferMethodCurrency according to the type and country of the bank account. However, we can't guarantee such modification won't break already existing and processing marketplaces and sellers.

The other solution I would suggest would be to change the Mirakl shop currency to USD the time to create the bank account.
Once the bank account is created, feel free to set the shop currency back to CAD and payments will be sent to HW in CAD and automatically converted by HW to be sent in USD to the bank account.

I'm closing this issue for now but don't hesitate to comment on it if you have any additional information you'd like to share.

Best,

**Comment by guillauc** [comment]
Hi @max6001,

Thanks for looking into our issue.

From what I understand, there's nowhere in Mirakl where we can change the shop currency, therefore your workaround doesn't work. 

Our CAD Mirakl environment allows US based Sellers to have US Bank Accounts, the connector should be able to create those US bank accounts in HW.

The only workaround we have right now is to create the Bank account manually in HW.

Thanks,
@guillauc

**Comment by javierpoloe2y** [comment]
Hi @guillauc,

You can ask Mirakl Support Team to enable multi-currency. More info in this [link](https://help.mirakl.net/bundle/customers/page/topics/Connectors/Magento2/user_guide/config_mirakl/config_currencies_mg2.htm).

This will give you the option to enable different currencies in the `Administration -> Languages and Currencies` section of the back office. 

![image](https://user-images.githubusercontent.com/97441435/219380873-1b929cb0-0604-4b8b-9301-b853167900f9.png)

After that, you will have the option to choose the currency in the shop:

![image](https://user-images.githubusercontent.com/97441435/219381151-7aceeae7-c803-4425-8aab-33134b74565a.png)

Of course if you prefer not to enable multi-currency, you can create the bank account manually in Hyperwallet (but remind that you will also need to enter the same information into Mirakl so the connector can associate the Hyperwallet bank account to the Mirakl shop).

**Comment by guillauc** [comment]
Hi @javierpoloe2y,

I don't think we will want to go that route, we want everything in CAD so that offers and prices are all in CAD.  Payments to sellers in CAD, converted in HW if necessary.  I believe playing with multiple currencies would be pretty risky right now.

I guess we will continue with the workaround we currently have, and yes, after we create the Bank account in HW, we copy the token back in Mirakl.

Thanks,
@guillauc

**Comment by javierpoloe2y** [comment]
Hi @guillauc,

We are going to fix this in a future patch that we are developing. In this new version the connector will set the bank account currency taking into account Hyperwallet country/currency restrictions and not only the Mirakl shop currency. 

So for your scenario it would automatically create US bank accounts with USD currency. The payments will still be made in CAD.

**Comment by guillauc** [comment]
Thanks @javierpoloe2y!!!

Great news!

**Comment by Valeeast** [comment]
> Hi @javierpoloe2y,
> 
> I don't think we will want to go that route, we want everything in CAD so that offers and prices are all in CAD. Payments to sellers in CAD, converted in HW if necessary. I believe playing with multiple currencies would be pretty risky right now.
> 
> I guess we will continue with the workaround we currently have, and yes, after we create the Bank account in HW, we copy the token back in Mirakl.
> 
> Thanks, @guillauc

**Comment by Valeeast** [comment]
> Hi,
> 
> We have our Mirakl environnement setup in CAD currency.
> 
> Some sellers are US sellers and have US Bank accounts. The connector fails to create the Bank account and giving the following message:
> 
> "code" : "EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED", "message" : "The bank account information provided is not configured for your program."
> 
> We found out that it's trying to add the Bank Account with: "transferMethodCountry": "US", "transferMethodCurrency": "CAD",
> 
> That doesn't work on the Hyperwallet side.
> 
> Is there a way to create those bank accounts automatically?
> 
> Thanks,
> 
> @guillauc

[](url)

**Comment by javierpoloe2y** [comment]
Hi @guillauc,

We have released version [4.19.0](https://github.com/paypal/mirakl-hyperwallet-connector/releases/tag/4.19.0), which automatically chooses a currency in Hyperwallet when the bank account is not compatible with the marketplace currency. With this release, you don't need to manually create a bank account in Hyperwallet.

**Comment by guillauc** [comment]
Hi @javierpoloe2y,

Thank you so much, can't wait to try it out!
Have a nice day,

@guillauc
