### ISSUE TITLE
[Question]: Spring Boot upgrade plans?

### ISSUE THREAD

**Issue by avrilfanomar** [paypal/mirakl-hyperwallet-connector#123]
As there are vulnerability issues in currently used version - https://mvnrepository.com/artifact/org.springframework.boot/spring-boot/2.6.6 , what are the plans to upgrade it?

**Comment by javierpoloe2y** [comment]
Hi @avrilfanomar,

We are planning to release a new version of the connector in the following weeks, we are going to update the Spring Boot dependency to the last 2.7.x version or to the last 2.6.x if we find compatibility issues.

We have also planned a new major release for the connector that runs on Spring Boot 3.0.x, but I can't give you details on the release date yet.

**Comment by javierpoloe2y** [comment]
Hi @avrilfanomar,

we have released version [4.19.0](https://github.com/paypal/mirakl-hyperwallet-connector/releases/tag/4.19.0) updating Spring Boot to 2.7.10.
