### ISSUE TITLE
[Issue]: Invoices not marked as PAID in Mirakl

### ISSUE THREAD

**Issue by pradeep-agnihotri** [paypal/mirakl-hyperwallet-connector#125]
### Describe the Issue

HWConnector picks up the payment file from Mirakl and connects with HyperWallet to transfer the funds to the Seller.
The funds are transferred successfully to the Seller, however the associated invoices with the payment file are not marked as PAID in Mirakl, giving an error as below;
`c.p.i.l.AbstractNotificationListener : Notification [wbh-ee68ddd7-58c9-40dd-86e4-b1056a51c049] could not be processed. Reason: [[400] The amount is incorrect for the accounting document with number '230201', actual: '767.36', expected: '737.41']`

This issues seems to be similar to the once previously reported by someone else also - 
https://github.com/paypal/mirakl-hyperwallet-connector/issues/102

CC: @javierpoloe2y , @max6001 

### Environment

Live/Production

### Version

4.14.0

### Expected Behavior

The HWConnector should mark the invoices associated with the Payment file as PAID.

### Actual Behavior

The HWConnector does not mark the manual and automatic invoice as PAID.

### Steps to Reproduce

1. There are multiple invoices for a single Seller (automatic invoices for commissions & order payments) and manual credit invoices.
2. The manual credit invoice - 000000230195 - $29.95
3. The Automatic Invoice - 000000230201 - $737.41
4. Mirakl generates a single payment file combining all the invoices (manual as well as automatic) totaling - $767.36
5. HWConnector picks up the payment file and sends payment instructions to HyperWallet.

### Relevant log output

```shell
.p.s.AcceptedPaymentNotificationStrategy : Creating payment confirmation request for invoice ID 230201 and amount 767.36
c.p.i.l.AbstractNotificationListener : Notification [wbh-ee68ddd7-58c9-40dd-86e4-b1056a51c049] could not be processed. Reason: [[400] The amount is incorrect for the accounting document with number '230201', actual: '767.36', expected: '737.41']
```

**Comment by max6001** [comment]
Hi @pradeep-agnihotri 
Thanks for reaching out.
That issue was already reported through https://github.com/paypal/mirakl-hyperwallet-connector/issues/102.

I'm afraid the outcome will the same we've provided back then.

**Comment by pradeep-agnihotri** [comment]
Hello @max6001 
Mirakl does provide the invoices that are pending to be marked as PAID, see below IV01 API.
/api/invoices?payment_status=PENDING&start_date=2023-02-08&type=ALL

I am not sure if Mirakl needs to be do anything here; the HWC would need to fetch the invoice via IV01 and then accordingly mark them as PAID using IV07.

**Comment by max6001** [comment]
@pradeep-agnihotri the HMC is only taking care of automatic billing invoices.
It ignores the manual credit and manual invoices as those money movement are already included into the automatic invoices generated.

Your issue is related to the fact the HMC is successfully pulling the automatic invoice from Mirakl.
It is sending that invoice for payment to Hyperwallet.
Hyperwallet does process that payment and notify the HMC via webhook.
The HMC is then trying to update the status of the payment in Mirakl but we are facing an error because Mirakl is expecting another amount than the one send to and via Hyperwallet.

The different options proposed to Mirakl are detailed in the other ticket.

**Comment by max6001** [comment]
@pradeep-agnihotri The HMC is using IV01 but ignoring manual credit note. Mirakl includes the amount of the manual credit notes into the next automatic invoice. This means that if the connector was processing manual credit notes, the amount of the credit notes will be payed two times, one in the credit note and one in the next invoice.
