### ISSUE TITLE
[Issue]: Invoice Amounts are incorrect when Manual Invoices are involved.

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#126]
### Describe the Issue

When paying out an Auto Invoice, the class PayeeInvoiceModelToHyperwalletPaymentConverter (Think that is the right class)

The convert uses the source.transfer amount. This is ok in most cases, however when manual invoices (credits and debits) are used, Mirakl has advised that a different calculation should be used.

This is the code for the payout to seller:

`@Override
	public HyperwalletPayment convert(@NonNull final InvoiceModel source) {
		final HyperwalletPayment target = new HyperwalletPayment();
		target.setProgramToken(
				invoicesHyperwalletSDKService.getProgramTokenByHyperwalletProgram(source.getHyperwalletProgram()));
		target.setDestinationToken(source.getDestinationToken());
		target.setClientPaymentId(source.getInvoiceNumber());
		target.setAmount(source.getTransferAmount());
		target.setCurrency(source.getCurrencyIsoCode());
		target.setPurpose(PURPOSE);

		return target;
	}`

We asked Mirakl support about this:
Their response was:

![Mirakl_Support_Response](https://github.com/paypal/mirakl-hyperwallet-connector/assets/104622039/a6a6a61d-822f-43f5-bc5b-3edfbed9ff31)

We are seeing that:
Given the below accounting document:
![Payable_Amount](https://github.com/paypal/mirakl-hyperwallet-connector/assets/104622039/e8bb9e13-7efa-4238-b072-89c3f1f6a96d)

The invoice generated shows:

![Mirakl_Invoice](https://github.com/paypal/mirakl-hyperwallet-connector/assets/104622039/09aa1cdb-18e9-454f-a738-5dc2099562e8)

The Connector gave an error that when confirming the payment with Mirakl - the amounts were incorrect.

I checked this with some test code:

`val miraklAccountingDocumentPaymentConfirmation = MiraklAccountingDocumentPaymentConfirmation().apply {
            amount = BigDecimal("35.76")
            currencyIsoCode = MiraklIsoCurrencyCode.GBP
            invoiceId = sellerInvoiceId
            transactionDate = Date.from(
                ZonedDateTime.parse("2023-05-19T01:00:03Z").toInstant(),
            )
        }
        return MiraklConfirmAccountingDocumentPaymentRequest(listOf(miraklAccountingDocumentPaymentConfirmation))`

And got the response:

Exception in thread "main" com.mirakl.client.core.exception.MiraklApiException: [400] The amount is incorrect for the accounting document with number '230415', actual: '35.76', expected: '35.56'
	at com.mirakl.client.core.internal.util.ResponseHelper.handleResponseErrorWithBody(ResponseHelper.java:94)
	at com.mirakl.client.core.internal.util.ResponseHelper.checkStatus(ResponseHelper.java:43)
	at com.mirakl.client.core.AbstractMiraklApiClient.put(AbstractMiraklApiClient.java:398)
	at com.mirakl.client.mmp.core.MiraklMarketplacePlatformFrontOperatorApiClient.confirmAccountingDocumentPayment(MiraklMarketplacePlatformFrontOperatorApiClient.java:207)
	at com.paypal.testing.ApiClientTest.confirmAccounting(ApiClientTest.kt:76)

I then looked at using Mirakl's method to calculate the actual payable amounts and printed out what the connector is performing:

`fun getInvoiceAmount() {
        createClient().use { client ->
            val request = MiraklGetInvoicesRequest()
            request.setShopId(invoiceShopId)
            val invoiceList = client.getInvoices(request)
            val results = invoiceList.invoices.filter { it.id.contains(sellerInvoiceId.toString()) }

            results.first().let {
                logger.info("Invoice: {}", it.id)
                logger.info("Amount Transferred: {}", it.summary.amountTransferred)
                logger.info("Amount Transferred To Operator: {}", it.summary.amountTransferredToOperator)
                logger.info("----------- Start of Calculation --------------------------")
                logger.info("Mirakl Formula Payout Total: {}", calculatedInvoiceAmount(it))
            }
        }
    }

    private fun calculatedInvoiceAmount(it: MiraklInvoice) =
        it.summary.totalPayableOrdersIT +
            it.summary.totalRefundCommissionsIT +
            it.summary.totalRefundOperatorPaidShippingChargesInclTax +
            it.summary.totalRefundOperatorRemittedTaxes +
            it.summary.totalCommissionsIT +
            it.summary.totalOperatorPaidShippingChargesInclTax +
            it.summary.totalOperatorRemittedTaxes +
            it.summary.totalRefundPayableOrdersIT +
            it.summary.totalSubscriptionIT`

Got the below output:

14:30:56.622 [main] INFO com.paypal.testing.ApiClientTest - Invoice: 230415
14:30:56.625 [main] INFO com.paypal.testing.ApiClientTest - Amount Transferred: 35.76
14:30:56.625 [main] INFO com.paypal.testing.ApiClientTest - Amount Transferred To Operator: 6.24
14:30:56.625 [main] INFO com.paypal.testing.ApiClientTest - ----------- Start of Calculation --------------------------
14:30:56.625 [main] INFO com.paypal.testing.ApiClientTest - Mirakl Formula Payout Total: 35.56

I also checked a standard invoice (with no manual invoices) and got the same amounts
(amount transferred + Formula payout are the same)

e.g.:

14:32:47.178 [main] INFO com.paypal.testing.ApiClientTest - Invoice: 230401
14:32:47.178 [main] INFO com.paypal.testing.ApiClientTest - Amount Transferred: 17.78
14:32:47.179 [main] INFO com.paypal.testing.ApiClientTest - Amount Transferred To Operator: 3.22
14:32:47.179 [main] INFO com.paypal.testing.ApiClientTest - ----------- Start of Calculation --------------------------
14:32:47.179 [main] INFO com.paypal.testing.ApiClientTest - Mirakl Formula Payout Total: 17.78

Please can you let us know whether this is in your list to change?

(I did notice there were exvat and incvat values too - which probably adds some complexity?)

Thanks,
Russ

### Environment

Live/Production

### Version

4.18.1

### Expected Behavior

Can payout invoices containing manual credits / debits (invoices) with correct amounts

### Actual Behavior

Payout created in Hyperwallet is for a different amount to what Mirakl is expecting.

### Steps to Reproduce

Create Orders + Manual Debits and Credits.
Await Mirakl Invoice
Test Payout (HMC creates invoice in UAT Hyperwallet)
Hyperwallet team contacted to perform payment.
Connector errors.

### Relevant log output

```shell
In the description above
```

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

Thanks for reaching out. That issue was already answered through https://github.com/paypal/mirakl-hyperwallet-connector/issues/102#issuecomment-1315257294

I'm afraid the outcome will be the same we've provided back then.

**Comment by RussGarratt** [comment]
Sorry, didn't realise this was already raised.
Did Mirakl give you a response?

We don't really want to get stuck in a stalemate.
Appreciate your decisions not to have logic in the connector and that it is essentially a mapper.

Regards,
Russ

**Comment by RussGarratt** [comment]
Hi @javierpoloe2y  @max6001

Is it possible that you can let us know who was the Mirakl contact please?
We are being requested by Mirakl to find out who in the product team this was for expediting.

Thanks and regards,
Russ

**Comment by max6001** [comment]
Hi @RussGarratt thanks for reaching out.

My Mirakl point of contact is a Senor Solution Technical Consultant based in Paris and in charge of handling relationships with the different Mirakl partners such as PayPal.

I'm afraid I can't share his name.

Best,

**Comment by RussGarratt** [comment]
I have been told by Mirakl that this now may be simpler:

Are we able to request this feature please?

Thanks,
Russ


We've just released a new feature that might help you and Hyperwallet. 
•	The IV07 API now includes a new field "confirm_all_linked_manual_documents". When set to "true", this feature enables the automatic payment of auto invoices, manual invoices, and manual credit notes in a single action.
•	The updated feature uses the total transfer amount instead of requiring separate amounts for each document, streamlining the accounting process.
•	For ease of transition, the new field will be set to false by default, maintaining the current process for operators who prefer it.
•	An added error message feature will alert you if an accounting document has already been paid, preventing duplication.
You can also find the documentation page related to the feature [here](https://help.mirakl.net/bundle/customers/page/topics/Mirakl/integrating_mirakl/pay_sellers/payment_confirmation.htm#ConfirmingthepaymentofallaccountingdocumentsatonceusingAPIIV07).

**Comment by RussGarratt** [comment]
hi @adbame 

Is it possible to get any update on this please?
Is this on your roadmap at all ? and if so - any ETA please?
Thanks,
Russ

**Comment by adbame** [comment]
Hi @RussGarratt 

I have no news about this
When I have some information let you know

**Comment by RussGarratt** [comment]
Not allowed to push to your repo but here would be the changes:


![changes](https://github.com/paypal/mirakl-hyperwallet-connector/assets/104622039/439bf822-cce6-470f-8ba8-7d2f1ac566c0)

**Comment by RussGarratt** [comment]
Created: https://github.com/paypal/mirakl-hyperwallet-connector/pull/148

**Comment by adbame** [comment]
Hi @RussGarratt 

A new release 5.2.0 has been published adding this new feature

Best Regards

**Comment by Tinamaam** [comment]
![Uploading 306712113-439bf822-cce6-470f-8ba8-7d2f1ac566c0.png…]()
