### ISSUE TITLE
DOB fields sometimes shifted back by a day

### ISSUE THREAD

**Issue by johnwright** [paypal/mirakl-hyperwallet-connector#13]
We've been seeing issues with DOB fields being shifted back by a day, and as far as I can tell Mirakl is behaving correctly. When these values are viewed in Hyperwallet, they are incorrect.

Mirakl represents dates as timestamps at midnight, taking daylight savings into account and converted to UTC. This means that the API will return values like:

|DOB|Mirakl timestamp|Notes|
|------------|------------------------|-------------------|
|1990-01-01 |1990-01-01T00:00:00Z|No daylight savings|
|1990-06-01 |1990-05-31T23:00:00Z|During daylight savings period|

This behaviour is deterministic, and since the connector is configured with the Mirakl service's time zone it should be possible to translate into correct dates for the Hyperwallet side.

**Comment by kcarta** [comment]
As this couldn't be reproduced and is no longer witnessed, we will close this ticket for now
