### ISSUE TITLE
[Issue]: UPGRADE 5.0.0 - ERROR CREATING INSTANCE ECS - AWS

### ISSUE THREAD

**Issue by mobbast** [paypal/mirakl-hyperwallet-connector#130]
### Describe the Issue

Hi Team,

I'd like to inform you that we are encountering some errorrs while trying to create instances on AWS. 

### Environment

Live/Production

### Version

5.0.0

### Relevant log output

```shell
ERROR org.springframework.boot.SpringApplication - Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'updateStoredItemLinksAspect' defined in URL [jar:file:/workspace/BOOT-INF/lib/hmc-invoices-5.0.0-plain.jar!/com/paypal/invoices/extractioncommons/aspects/UpdateStoredItemLinksAspect.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'accountingDocumentsLinksServiceImpl' defined in URL [jar:file:/workspace/BOOT-INF/lib/hmc-invoices-5.0.0-plain.jar!/com/paypal/invoices/extractioncommons/services/AccountingDocumentsLinksServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'miraklInvoiceLinksServiceImpl' defined in URL [jar:file:/workspace/BOOT-INF/lib/hmc-invoices-5.0.0-plain.jar!/com/paypal/invoices/extractioncommons/services/MiraklInvoiceLinksServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'stageChangesMiraklClient' defined in URL [jar:file:/workspace/BOOT-INF/lib/hmc-infrastructure-5.0.0-plain.jar!/com/paypal/infrastructure/mirakl/client/StageChangesMiraklClient.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'ignoredShopsFilter' defined in URL [jar:file:/workspace/BOOT-INF/lib/hmc-infrastructure-5.0.0-plain.jar!/com/paypal/infrastructure/mirakl/client/filter/IgnoredShopsFilter.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'hyperwalletProgramsConfiguration': Injection of autowired dependencies failed
```

**Comment by javierpoloe2y** [comment]
Hi @mobbast,

That error happens when the environment variables for program configuration are not correctly set. Please review the [upgrade guide](https://paypal.github.io/mirakl-hyperwallet-connector/component-hmc/upgrade/upgrade.html) if you are upgrading from a 4.x version or take a look at the [program configuration guide](https://paypal.github.io/mirakl-hyperwallet-connector/component-hmc/configuration/programs/programs.html).

**Comment by mobbast** [comment]
Hi Javier,

we have resolved first problem but now we have this have this error:

_org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'financialReportServiceImpl' defined in URL [jar:file:/workspace/BOOT-INF/lib/hmc-reports-5.0.0-plain.jar!/com/paypal/reports/services/impl/FinancialReportServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'reportsBraintreeTransactionsExtractServiceImpl' defined in URL [jar:file:/workspace/BOOT-INF/lib/hmc-reports-5.0.0-plain.jar!/com/paypal/reports/services/impl/ReportsBraintreeTransactionsExtractServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'getBraintreeSDKClient' defined in class path resource [com/paypal/reports/ReportsConfiguration.class]: Failed to instantiate [com.braintreegateway.BraintreeGateway]: Factory method 'getBraintreeSDKClient' threw exception with message: **merchantId needs to be set**_

**But in documentation we reed that this variable in not mandatory: PAYPAL_BRAINTREE_MERCHANT_ID NO**

This is a list of variables that we have
PAYPAL_MIRAKL_OPERATOR_API_KEY=
PAYPAL_MIRAKL_ENVIRONMENT=
PAYPAL_HYPERWALLET_API_SERVER=
PAYPAL_HYPERWALLET_API_USERNAME=
PAYPAL_HYPERWALLET_API_PASSWORD=
PAYPAL_HYPERWALLET_PROGRAM_TOKENS=
PAYPAL_HYPERWALLET_PROGRAMS_USERTOKENS=
PAYPAL_HYPERWALLET_PROGRAMS_PAYMENTTOKENS=
PAYPAL_SERVER_EMAIL_HOST=
PAYPAL_SERVER_EMAIL_PORT=
PAYPAL_MAIL_SMTP_AUTH=
PAYPAL_MAIL_USER_NAME=
PAYPAL_MAIL_USER_PASSWORD=
PAYPAL_MAIL_SMTP_STARTTLS_ENABLE=
PAYPAL_HYPERWALLET_PROGRAMS_BANKACCOUNTTOKENS=
PAYPAL_RABBITMQ_USERNAME=
PAYPAL_RABBITMQ_PASSWORD=
PAYPAL_SPRING_PROFILE_ACTIVE=
SPRING_PROFILE_ACTIVE=
PAYPAL_MOCK_SERVER_URL=
PAYPAL_HYPERWALLET_PROGRAMS_NAMES=
PAYPAL_HYPERWALLET_PROGRAMS_IGNORED=

Can you help us understand problem?

THX
Enrico

**Comment by javierpoloe2y** [comment]
Hi @mobbast,

As the documentation says `PAYPAL_BRAINTREE_MERCHANT_ID` it's not mandatory. In fact, if you don't set that environment variable, the connectors sets a default `not-set` value so it can start properly. This is done in the `application.properties` file:

```properties
hmc.braintree.connection.environment                 = ${PAYPAL_BRAINTREE_REPORT_ENVIRONMENT:sandbox}
hmc.braintree.connection.merchantId                  = ${PAYPAL_BRAINTREE_MERCHANT_ID:not-set}
hmc.braintree.connection.publicKey                   = ${PAYPAL_BRAINTREE_PUBLIC_KEY:not-set}
hmc.braintree.connection.privateKey                  = ${PAYPAL_BRAINTREE_PRIVATE_KEY:not-set}
```

I know that in older versions internal properties files of the connector needed to be modified to configure things like multiple Hyperwallet programs, but it's no longer necessary. Did you modify any internal property files? Could you try to clone the repository in another directory and try to build and run the connector again?

Also, some of the environment variables that you have are no longer needed like `PAYPAL_HYPERWALLET_PROGRAM_TOKENS`, `SPRING_PROFILE_ACTIVE`, `PAYPAL_MOCK_SERVER_URL`, `PAYPAL_RABBITMQ_USERNAME`. They don't have any negative impact, but I recommend cleaning your environment variables and keeping only the ones needed in the new version.

In the [pre-requisites page](https://paypal.github.io/mirakl-hyperwallet-connector/component-hmc/prerequisites/prerequisites.html) of the online documentation you can see the minimum set of variables needed by the connector. Also, take a look at the migration guide to see if you need to migrate any other additional variable.

**Comment by mobbast** [comment]
Hi Javier,

thx 4 support!

We have resolved!
