### ISSUE TITLE
[Issue]: Hyperwallet sends out stale webhooks on KYC

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#134]
### Describe the Issue

We are in discussion with Hyperwallet support, but they have suggested raising a ticket with you too:

> Hi Russ,
Thank you for your input, please, open a ticket on the HMC github page  explaining in details this scenario and the team in charge of the connector will be able to assist you further since the connector is managed by them.
We will keep investigating in our end too.

Once KYC is verified Hyperwallet sends a webhook.

What we are seeing is that a GET on the User (in Hyperwallet) - shows them as KYC verified.

What we see on the webhook is that: the Letter of Authorisation is still REQUIRED

GET call to user:

"verificationStatus": "VERIFIED",
"businessStakeholderVerificationStatus": "VERIFIED",
"letterOfAuthorizationStatus": "VERIFIED",
"taxVerificationStatus": "NOT_REQUIRED",

Webhook:

"businessStakeholderVerificationStatus": "VERIFIED",
"letterOfAuthorizationStatus": "REQUIRED",
"taxVerificationStatus": "NOT_REQUIRED",

BusinessKYCUserStatusNotificationStrategy (correct logic):

`
final String verificationStatus = Optional.ofNullable(incomingNotification.getVerificationStatus())
				.map(Enum::name).orElse(null);
		final String businessStakeHolderStatus = Optional
				.ofNullable(incomingNotification.getBusinessStakeholderVerificationStatus()).map(Enum::name)
				.orElse(null);
		final String letterStatus = Optional.ofNullable(incomingNotification.getLetterOfAuthorizationStatus())
				.map(Enum::name).orElse(null);

		final Triple<String, String, String> statuses = Triple.of(verificationStatus, businessStakeHolderStatus,
				letterStatus);
		if (REQUIRED.equals(statuses.getLeft()) || REQUIRED.equals(statuses.getMiddle())
				|| REQUIRED.equals(statuses.getRight())) {
			return MiraklShopKycStatus.REFUSED;
		}
		if (UNDER_REVIEW.equals(statuses.getLeft()) || UNDER_REVIEW.equals(statuses.getMiddle())
				|| UNDER_REVIEW.equals(statuses.getRight())) {
			return MiraklShopKycStatus.PENDING_APPROVAL;
		}
		return MiraklShopKycStatus.APPROVED;
`

(I think the code is fine)

This is what support responded with:

> Our Tech Team would like to clarify the following.
- Are you updating the KYC status on your end extracting the data from the webhook only? Through a GET call using the user token as endpoint where everything is verified is not updating it on your end?
If you do a GET call on the user token and not webhook, you can get the overall updated status of that wallet/user. Because the webhook are subset of each events, by calling a particular webhook, may not provide most up-to-date information.

I appreciate the connector is largely webhook only as far as I am aware? (for updates / incoming) 

Whilst this feels the wrong area to post this (on here)

I would appreciate if you could also confirm to Hyperwallet that this is probably a bug on their side.
They may want you to make calls to confirm user details though off the back of a webhook (nice huh?)

This is impacting us, as we go into this cycle of:

* Verified in Hyperwallet
* KYC Failed in Mirakl

(We don't know how to monitor this either - as we would't know to check - it could be a valid Failure)

Please can you guys help?

Thanks and regards,
Russ

### Environment

Live/Production

### Version

4.18.1

### Expected Behavior

User status is in sync with Hyperwallet

### Actual Behavior

User is Verified in Hyperwallet but REFUSED in Mirakl

### Steps to Reproduce

Just do a KYC flow it seems.

This seems more of an issue on Hyperwallet's side

Ticket in Hyperwallet support: 3290

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

I need to review it in more detail, but a priori I can tell you:

- Yes, the connector is mostly webhook only, so we expect that processing only the webhooks, the final status of the KYC is correct. The connector ensures that duplicated or out-of-order events are discarded, so we always have the final version of the statuses.
- I know that you are still on v4.18.1, but v5.0.0 includes a feature to dump in the logs all of the HTTP traffic generated or received by the connector (more info [here](https://paypal.github.io/mirakl-hyperwallet-connector/component-hmc/configuration/togglefeatures/togglefeatures.html#_http_traffic_logging). Perhaps this is useful for you in your UAT environment.

**Comment by RussGarratt** [comment]
hi @javierpoloe2y 

We are using 5.0.0 in UAT at the moment.
I believe this is a Hyperwallet issue only with the LoA (Letter Of Authorization) field of the user.

They should ideally fix it so that the webhook shows what shows on a GET to the user token, otherwise the connector can't do much other than refuse the kyc.

Regards,
Russ

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

Since the Hyperwallet team is currently investigating the problem with the webhook, I will close this issue. Feel free to reopen it if you need more support on this.
