### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by sairumea** [paypal/mirakl-hyperwallet-connector#136]
### Describe the Issue

hmc.braintree.connection.environment                 = ${PAYPAL_BRAINTREE_REPORT_ENVIRONMENT:sandbox}
hmc.braintree.connection.merchantId                  = ${PAYPAL_BRAINTREE_MERCHANT_ID:not-set}
hmc.braintree.connection.publicKey                   = ${PAYPAL_BRAINTREE_PUBLIC_KEY:not-set}
hmc.braintree.connection.privateKey                  = ${PAYPAL_BRAINTREE_PRIVATE_KEY:not-set}

### Environment

Live/Production

**Comment by devchristina** [comment]
close, not planned.
