### ISSUE TITLE
[Issue]: Mirakl SDK is outdated

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#139]
### Describe the Issue

One of our team have identified an issue where the shop state was set to TERMINATED in Mirakl, however, the Mirakl SDK being used by the connector does not have this in the enum of MiraklShopState ( Using 6.8.0). 

This was introduced in SDK 6.33.0   (see: https://help.mirakl.net/bundle/customers/page/topics/Connectors/SDK/java/java_downloads.htm)

When the S20 call responds with a status of TERMINATED an exception is thrown as it cannot be marshalled to the MiraklShopState enum.

### Environment

Live/Production

### Version

5.0.0

### Expected Behavior

Able to support any enumerated types added by Mirakl

### Actual Behavior

Exception thrown from the connector and S20 call cannot complete.
Creates / Updates are not sent to Hyperwallet

### Steps to Reproduce

Set Shop State to Terminated in Mirakl
Attempt Professional Sellers / Sellers extract
Observe error

**Comment by Magdoosha** [comment]
Hi @RussGarratt Thank you for raising the issue. We are in the process of reviewing this now and will be in touch shortly. Thanks, Magda

**Comment by adbame** [comment]
Hi @RussGarratt We have published a new version (5.1.0) with the fix to support shops in the "TERMINATED" state and Mirakl SDK updated to the latest version available (6.37.0)

Thanks

**Comment by RussGarratt** [comment]
Thanks @adbame and @javierpoloe2y  we will look to update the connector over our next sprint or so in UAT and feed back if any issues

**Comment by adbame** [comment]
I have closed this issue. Feel free to reopen it if you need more support on this.
