### ISSUE TITLE
[Issue]: Unable to request negative transfer to operator amount

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#151]
### Describe the Issue

This particular issue arises when we use the Mirakl feature of "Manual Credits" which essentially means a seller is being credited some amount. (Conceptually, the 'creditor' would need to credit the funding account to cover this potential payout to seller since it is just granted when doing a manual credit)

The scenario would be something like this:

Assume a seller has simply sold £10 of orders  (Which result in £8 to seller and £2 to Operator for commissions + subscriptions)

Now through some disputes the operator has granted the seller £5 in Manual Credits.
The mirakl process is to 'roll-up' manual invoices / credits into the next Automatic invoice.

As a result:

* The seller is now due to be paid £13  (amount_transferred) - because of the £8 in orders sold plus the operator £5 manual credit
* The operator is now due to be paid -£3 -    (£2 from commissions minus the £5 from the Manual credit)

The connector simply maps what is in the Mirakl invoice fields:

```
@Service
public class MiraklInvoiceToInvoiceModelConverter implements Converter<MiraklInvoice, InvoiceModel> {

	@Override
	public InvoiceModel convert(final MiraklInvoice source) {

		if (Objects.isNull(source)) {
			return null;
		}

		//@formatter:off
		return InvoiceModel.builder()
				.shopId(String.valueOf(source.getShopId()))
				.transferAmount(source.getSummary().getAmountTransferred().doubleValue())
				.transferAmountToOperator(source.getSummary().getAmountTransferredToOperator().doubleValue())
				.subscriptionAmountVat(Math.abs(source.getSummary().getTotalSubscriptionIT().doubleValue()))
				.orderCommissionAmountVat(Math.abs(source.getSummary().getTotalCommissionsIT().doubleValue()))
				.invoiceNumber(source.getId()).currencyIsoCode(source.getCurrencyIsoCode().name()).build();
		//@formatter:on
	}
}
```

This then fails when trying to create the Payment in Hyperwallet for Negative amount (as Hyperwallet can only process a positive transfer amount)

If the operator has credited the Funding account to cover for this - the connector will never know about it.

We are also in conversation with Mirakl , who are advising to perform the calculation excluding the credits (Deja Vu?)
but are also trying to progress other options.

One solution would be to enable a toggle on the connector that could exclude the credits.

We are reaching out to try and get some sort of consensus as to how this should be handled

![Negative_Invoice](https://github.com/user-attachments/assets/b5222fff-4b4d-47bd-b758-fbaf4849201d)

### Environment

Test/UAT

### Version

5.2.0

### Expected Behavior

Operator payout includes commissions and subscriptions only (so that an amount is always transferred)

### Actual Behavior

```
"summary": {
                "amount_transferred": 9362.56,      (Mapped as amount payable to seller from Escrow)
                "amount_transferred_to_operator": -9355.06,   (Mapped as amount payable to Operator)
                "total_commissions_excl_tax": -1.15,
                "total_commissions_incl_tax": -1.38,
                "total_fee_excl_tax": 0.00,
```

the large credits cause the Connector to fail on the Invoice job whilst submitting the invoiceId-operatorFee

### Steps to Reproduce

Create an/some orders in Mirakl.
Create an/some manual credit(s) in Mirakl which total more than the commission amount the operator will receive.
Await automatic invoice generation from Mirakl
Trigger connector invoice batch job

or)

alternatively, call Hyperwallet API with a negative balance

### Relevant log output

```shell
Can be retrieved from logs if needed but this is a Hyperwallet API error response for negative balance, which will be seen on any createpayment request with a negative balance.
```

**Comment by max6001** [comment]
Hi @RussGarratt,

Thanks for reaching out!

As we discussed previously, the HMC role is to take data from Mirakl and send it over the HW to execute the relevant payouts. The HMC is not meant to touch anything related to amounts (no re-calculation whatsoever).

I would expect Mirakl to handle the edge case you've described by potentially rolling over the platform fees to the next billing cycle or keeping any track of it so it can be send to the HMC separately.

At best we could adjust the HMC to not try to make negative value payout in HW so it won't display any error but I beleive we still want to track such edge cases when they occure so at least the operator can act on it.

What do you think?

Max

**Comment by RussGarratt** [comment]
Hi @max6001 

I appreciate the role of the connector and not wanting to take on the business logic.

I suppose the issue is with the calculation in the Mirakl side:

amount to operator = subscription fees + commissions - manual credits to seller (operator granted)

Mirakl also offer something in their payout solution which transfers from a 'buffer' account in the negative cases. But appreciate that is probably a large change in the connector. (if negative transfer from funding account B into funding account A)
Not sure whether this would be an option?

We would want to ensure: the commission + subscriptions are catered for / retained

So if the process was manual: (e.g. operator tops up escrow) with credits
We would still need to know the subscription and commission amounts
This would require the business logic changes to the connector

Would it be possible to change to use a top-up account transfer in the cases of negative balance? (perhaps this could be a toggle?)

The concept is somewhat the same though, a pay-in from another source.

Looking for some suggestions / ideas really.

Other options are largely business process

Regards,
Russ

**Comment by RussGarratt** [comment]
hi @max6001 

If I were to submit a PR with:

A feature that could be toggled on (off by default) - to take negative amounts and transfer from another given account, that was tested, would it likely be accepted by the community / team to the project?

Just checking feasibilitiy,

Thanks
Russ

**Comment by max6001** [comment]
@RussGarratt sorry for the delay.
We will totally review it and if there is no "harm" we will accept it.

We developed the HMC to allow people to contribute to it so please submit the PR.

Max
