### ISSUE TITLE
[Issue]: Layer 7 encryption set-up failure

### ISSUE THREAD

**Issue by pfalkner** [paypal/mirakl-hyperwallet-connector#26]
### Describe the Issue

Kingfisher are trying to enable Layer 7 encryption on the HMC. They have run some tests but are seeing the following error in the logs:

![image](https://user-images.githubusercontent.com/5063716/149165417-42b062bb-a168-4902-982b-9cdb9c5e4c76.png)

We've had feedback from HW engineering that the requests coming from the HMC are missing delimiters ("."). As Layer 7 encryption enablement is a config setting from the merchants perspective, it suggests there may be an issue in the HMC code? Please can you investigate.

### Environment

Test/UAT

### Version

4.6.1

### Expected Behavior

successful comms between HMC and HW in the transmission of API request.

**Comment by loopion** [comment]
This was a port issue setup. It's resolved and working properly.
