### ISSUE TITLE
[Issue]: Valid KYC documentation types not supported in HMC

### ISSUE THREAD

**Issue by pfalkner** [paypal/mirakl-hyperwallet-connector#30]
### Describe the Issue

Hi guys - we have uncovered an issue regarding supported doc types for the KYC process on the Hyperwallet side. Previously, for Business Seller verification, the expected doc type was Article of Incorporation (INCORPORATION). However, we have since discovered that the following values are also legitimate:
BUSINESS_REGISTRATION
OPERATING_AGREEMENT

Currently, when the HMC receives a webhook from HW with an update to the verification status, it is rejecting the webhook because it does not expect these doc types. This means a Verified status can't be reflected in Mirakl because the Webhook for Verified status is not accepted.

The HMC will need to be updated to support these new doc types in order to work correctly with the Managed Payee Verification flow, because in the Managed flow the seller is able to select any one of the 3 doc types from the HW UI when submitting their docs.

### Environment

Live/Production

### Expected Behavior

HMC should accept doc type values:

INCORPORATION
BUSINESS_REGISTRATION
OPERATING_AGREEMENT

### Actual Behavior

HMC is only accepting doc type INCORPORATION

**Comment by dpuye2y** [comment]
Hi Paddy,

Could you let us know the connector version KF is currently running?
We would it in order to check the possible solutions and balance between delivery time and cost.

**Comment by max6001** [comment]
Hi Paddy,
We have added support for the additional document types which went into release 4.7.1.
Don't hesitate to reach out if you ever need anything else,
Best,
