### ISSUE TITLE
[Issue]: class name and .java file are different

### ISSUE THREAD

**Issue by apopescu** [paypal/mirakl-hyperwallet-connector#31]
### Describe the Issue

Hello everyone,

I tried to build the 4.7.0 release using Docker container and i get an error during the **Task :kyc:compileJava** about Java class name and related .java filename, which are not the same.

The error is this one:
```
mirakl-hyperwallet-conn:ctor/kyc/src/main/java/com/paypal/kyc/listeners/KycUserEventListener.java:19: error: class KYCUserEventListener is public, should be declared in a file named KYCUserEventListener.java
public class KYCUserEventListener extends AbstractNotificationListener<KycUserEvent> {
```

Actually, the 4.7.0 release has a wrong class name/filename, there is **KycUserEventListener.java** as filename and **KYCUserEventListener** as class name. One of the 2 should be changed to match the other one (KYC -> Kyc). Before the 4.7.0 release they matched, so no error occurred.

### Environment

Development

### Version

4.7.0

### Expected Behavior

**Task :kyc:compileJava** should have completed successfully.

### Actual Behavior

Task :kyc:compileJava FAILED
/workspace/mirakl-hyperwallet-connector/kyc/src/main/java/com/paypal/kyc/listeners/KycUserEventListener.java:19: error: class KYCUserEventListener is public, should be declared in a file named KYCUserEventListener.java
public class KYCUserEventListener extends AbstractNotificationListener<KycUserEvent> {

### Steps to Reproduce

1. Go to project folder
2. ./gradlew buildDockerCompose

**Comment by apopescu** [comment]
https://github.com/paypal/mirakl-hyperwallet-connector/commit/41d69ea7449f20665757e3018fff7a4e1c34b4ce#diff-dfb8e2ec53f4d55028c26ac194b89e04f03732438953b2258ba9b5d252aa0d8dR19

**Comment by javierpoloe2y** [comment]
Hi @apopescu,

Thank you for identifying and reporting this issue. We have already fixed the case sensitivity problems and have generated a new [4.7.1 release](https://github.com/paypal/mirakl-hyperwallet-connector/releases/tag/4.7.1).
