### ISSUE TITLE
[Question]: Invalid Bank Account Issue

### ISSUE THREAD

**Issue by leirwin** [paypal/mirakl-hyperwallet-connector#33]
Hello!
Two sellers have bank account tokens in their Mirakl account. We've now realized that they've not been paid for 2 billing cycles because because of an invalid bank account. 
When we ping Hyperwallet bank account API, we can see the bank account is invalid for both sellers.
Our understanding from Hyperwallet is that the bank account token is only created when a bank account successfully creates in Hyperwallet. 
We've instructed the sellers to validate their bank account in Mirakl, but we're still seeing the invalid bank account details via Hyperwallet API. The sellers also have the original bank account token in Mirakl.
We have a PROD support ticket open with Hyperwallet, but I was wondering if you could provide any feedback on the above behavior?
Laura Irwin - Mirakl

**Comment by leirwin** [comment]
Hi Following up on this...
What we've heard from Hyperwallet support is the following:
_The first is that the company or the payee have an open bank account related to their HyperWallet account and they find there is some wrong information, so if the bank account status is "Enabled", they should be able to update information as they will and keep the same token.

The second case is the one we faced with the bank account that had some wrong information and tried to process a transfer and returned the "Invalid" status. In this case, there is no possibility to update it, so they should create a new one with the correct information, generating a new token._

In the 2nd case when a payment fails, what are the steps the seller/operator needs to take in Mirakl to resolve the invalid bank account?

**Comment by quim3ra** [comment]
HI @leirwin ,

This is how the connector behaves:

- If the shop has a bank account token, that means that at some point the connector was able to create the bank account in HW with the data stored in mirakl.
- If the seller passed the KYC process and there were orders placed within Mirakl and a invoice was generated for that seller the connector will try to make a payment using the bank account token stored in the shop.

If for any reason the bank account token for the seller is disabled, the connector will simply retry the payments again on every run of the Invoice Extract job

**Comment by leirwin** [comment]
Hi @quim3ra -
What we're hearing from Hyperwallet PROD support is that the seller payment failed because the bank account is invalid. They confirmed that at any point AFTER a payment fails, the bank account needs to be updated which would generate a NEW token, that is different from the one in the seller's account in Mirakl. What we're trying to confirm is how we should move forward in this scenario? The TRM in mirakl is not updating to the new token. Does this need to be done manually?

**Comment by max6001** [comment]
Hi Laura,

Thanks for reaching out! While we are thinking on how we could automatically handle that scenario in the HMC I would suggest the following:
1/ Marketplace operator or seller deletes the TRM from Mirakl and update their bank details
2/ HMC will automatically create/re-create a new bank account in HW and update Mirakl with the new TRM.

Don't hesitate to re-open this issue if that doesn't fix the problem.

Max
