### ISSUE TITLE
[Question]: CAD Payment Support

### ISSUE THREAD

**Issue by leirwin** [paypal/mirakl-hyperwallet-connector#34]
Hello -
The HMC solution guide says that it supports seller payments in CANADIAN bank account schemes from Mirakl. However, when looking at the Hyperwallet API documentation, I see that a required field for the creation of a Canadian bank account is:
bankId | The exact 3 digit bank code.Validation Pattern: ^[0-9]{3}$

My assumption is that this would map to the below field in a Mirakl Canadian bank account scheme:
Institution Number - Institution number (3 digits)

However, I do not see this Mirakl <> Hyperwallet field mapping in the solution guide.

Can you confirm that HMC will support sending the institution number to Hyperwallet to the bankId technical field?

Thank you!

**Comment by max6001** [comment]
You are correct as Mirakl Insitution Number is mapped to the Hyperwallet bankId attribute so it will work as expected. We will update the SDD to reflect this as it is currently only appearing IBAN and US info.
