### ISSUE TITLE
[Issue]: Managing out-of-sync webhooks

### ISSUE THREAD

**Issue by pfalkner** [paypal/mirakl-hyperwallet-connector#35]
### Describe the Issue

The HW platform currently doesn't guarantee that webhooks will be sent in the order in which they are created. This opens the possibility that statuses will be incorrectly recorded within Mirakl. 

Recently we’ve encountered an issue with one of Kingfisher’s sellers’ verification status being out of sync between Hyperwallet and Mirakl. Here’s the sequence of events:
 
17:25

- webhook 1 generated: HW webhook "USERS.UPDATED.VERIFICATION_STATUS.REQUIRED”

17:27

- webhook 2 generated: HW webhook “USERS.UPDATED.VERIFICATION_STATUS.VERIFIED”
- webhook 2 was sent by HW
- HMC received the webhook
- HMC updated Mirakl with seller status = verified

17:30

- Webhook 1 was sent by HW
- HMC received the webhook
- HMC updated Mirakl with seller status = rejected

 
The issue for out of sync was caused by HW sending webhook 1 after it already sent webhook 2 (i.e. out of order). However, Hpyerwallet [documentation on webhooks](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.hyperwallet.com%2Fcontent%2Fwebhooks%2Fv1%2Fintegration&data=04%7C01%7Cpfalkner%40paypal.com%7C94c15ff6a7d845257c8f08da01d6b992%7Cfb00791460204374977e21bac5f3f4c8%7C0%7C0%7C637824318994582684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JpUdpG0jbnzqMUq1zcvuzThPsI7k82x67ALBpQE6qgk%3D&reserved=0) did state that this is something the integration needs to consider as “Hyperwallet does not guarantee that webhooks will be sent in the order in which they are generated. Hyperwallet advises that you make use of the createdOn timestamp included in the webhook notification object to handle the ordering of events.” And I’ve confirmed with the Hyperwallet team that there’s no plans to introduce a queueing system for webhook to ensure webhooks are sent in the order in with they are generated.
 
While the impact has been low so far (it has happened to KF and other merchants on the solution occasionally), there’s a risk of this happening and causing ongoing reconciliation headache for the operator, especially in the situation where HW generates webhooks in quick succession (like for sellers who get automatically verified by HW system). Can the team do a deep dive of this use case and suggest what can be done to avoid this?

### Environment

Live/Production

### Version

4.6.3

### Expected Behavior

Ideally, webhook sequencing should be identified to ensure that out-dated updates can be ignored

### Actual Behavior

HMC takes each webhook in the order received, and updates Mirakl with the relevant webhook contents.

**Comment by max6001** [comment]
Hi Paddy,
This issue got resolved with the release of version 4.7.2 end of March.

I'm closing this ticket and don't hesitate to get back to us if needed.

Best,
