### ISSUE TITLE
[Issue]: HMC version upgrade issue - not picking a specific seller

### ISSUE THREAD

**Issue by siprapattanaik** [paypal/mirakl-hyperwallet-connector#51]
### Describe the Issue

We recently upgraded to 4.12.0.We are seeing below exception and we are testing different flows.One of the seller which is a Professional seller is not getting picked up by the Professional seller extract job.However thsi is getting picked by the regular seller job.The seller is declared as a professional seller. The seller id is 2000.q 

### Environment

Test/UAT

### Version

4.12.0

**Comment by Adel6556655** [comment]
[Money Request Transaction details - PayPal.pdf](https://github.com/paypal/mirakl-hyperwallet-connector/files/9045263/Money.Request.Transaction.details.-.PayPal.pdf)

**Comment by Adel6556655** [comment]
- [ ]

**Comment by javierpoloe2y** [comment]
Hi @siprapattanaik, thanks for the report, but you didn't provide the log trace with the exception that you mentioned.

Looking at the code, that shouldn't happen. Perhaps is a misleading log message, but we would need the log to see what's happening.

**Comment by siprapattanaik** [comment]
Hi @javierpoloe2y  , Since the job is not picking up , there is no logs to provide . Is there something we can get onto a call ?

**Comment by Dogpound23** [comment]
Need help

**Comment by javierpoloe2y** [comment]
> Hi @javierpoloe2y , Since the job is not picking up , there is no logs to provide . Is there something we can get onto a call ?

@siprapattanaik, but you know that a professional seller is being picked by the individual seller job, so you should have some form of log of information about what's happening. We need all the possible details to be able to make a diagnostic. If you are able to provide more detailed information, we will be glad to help you.

**Comment by max6001** [comment]
Hi @siprapattanaik
Are you still witnessing that issue after updating to the latest version of the connector?
Thanks in advance for your return,
Best,
