### ISSUE TITLE
[Issue]: HMC version upgrade to 4.13.1 and issue of maxretry

### ISSUE THREAD

**Issue by siprapattanaik** [paypal/mirakl-hyperwallet-connector#62]
### Describe the Issue

Recently we migrated to 4.13.1 and we are seeing issues of maxretry .The error looks something like below. My question is how do we avoided this max retry attempt ? Is there any config  for the same.

Max retry attempts reached when processing item [2107], the item won't be processed anymore

### Environment

Live/Production

### Version

4.13.1

**Comment by javierpoloe2y** [comment]
Hi @siprapattanaik, currently we don't have a configuration option to adjust the number of retries. Now it's fixed to 5 retries.

Even though the log says:

```
Max retry attempts reached when processing item [2107], the item won't be processed anymore
```

It doesn't mean that item 2107 won't be processed never in the future. This log message is related only to the retry jobs, which take a previously failed item and tries to process it again.

Every time that the item changes in Mirakl it's processed again by the extract jobs and its retry counter is reset to 0. Also if you do a manual run of the job the item will be processed again even when it hasn't changed.

Probably a better log message would have been something like:

```
Max retry attempts reached when processing item [2107], the item won't be automatically retried again. 
It will be processed again if the item has any changes or if a manual job execution is done.
```

**Comment by max6001** [comment]
Closing this issue as Javier's response seems to have answered the question.
