### ISSUE TITLE
[Issue]: The payment status is FAILED

### ISSUE THREAD

**Issue by packs1200** [paypal/mirakl-hyperwallet-connector#66]
### Describe the Issue

Hi team,

We are receiving a error when hyperwallet connector is trying to pay the invoice to one of our customers. I have told with yours service department to try to check if there is a field value wrong, but they say that all is correct and recommend me to open this issue ticket.

Log error:
com.hyperwallet.clientsdk.model.HyperwalletPayment@53bf7abe[amount={amount},clientPaymentId=230202-operatorFee,createdOn=<null>,currency=EUR,destinationToken={destinationToken},expiresOn=<null>,links=<null>,memo=<null>,notes=<null>,programToken={programToken},purpose=OTHER,releaseOn=<null>,status=<null>,token=<null>,inclusions={destinationToken,programToken,amount,clientPaymentId,purpose,currency}]

Mail notification error:
Something went wrong creating payment for invoice [230202] {exceptionMessage=The client payment reference has already been used for a different transaction,error=DUPLICATE_CLIENT_REFERENCE[[code=DUPLICATE_CLIENT_REFERENCE,fieldName=<null>,message=The client payment reference has already been used for a different transaction,relatedResources=<null>]]}

I will contact with your partners for they can send you the log files (for security) 

Thank you in advance

### Environment

Live/Production

### Version

4.3.2

### Expected Behavior

Pay the invoice

### Actual Behavior

It's not paying the invoice

### Steps to Reproduce

Every 15 days Hyperwallet connector is generating the partner invoice and then it's necessary to pay it

**Comment by max6001** [comment]
Hi @packs1200 
Thanks for reaching out!
The error returned "The client payment reference has already been used for a different transaction" seems to be a valid error thrown by Hyperwallet. It seems that you are passing a unique ID for the invoice payment that has already been used/processed by Hyperwallet on another payment.

I would recommend to get back to David to check together on the HW side what is going on.

We keep this issue opened in the meantime in case the HMC might be at fault.

Don't hesitate to let us know if you need anything else,

Best,

**Comment by max6001** [comment]
Good Morning @packs1200 
Another speculation of what could be happening is that the same payout request is being sent by the HMC to Hyperwallet as you are using a very old version of the HMC where things like that could happen.
Additionally to the error, are you witnessing any problem on HW or Mirakl side? I mean, is the payment going through? Is the invoice status properly updated on Mirakl side?
