### ISSUE TITLE
[Question]: Manual Credit Variable Question

### ISSUE THREAD

**Issue by leirwin** [paypal/mirakl-hyperwallet-connector#72]
Hello! 
Does the variable PAYPAL_HYPERWALLET_OPERATOR_CREDIT_NOTES_ENABLED need to be set to TRUE for manual credits to be paid to sellers? Will manual credits be taken into account for seller payments in the normal automatic invoice?

Thank you!

**Comment by javierpoloe2y** [comment]
Hi @leirwin,

Yes if `PAYPAL_HYPERWALLET_OPERATOR_CREDIT_NOTES_ENABLED` is `false` manual credits won't be retrieved from Mirakl. Remember that its default value is `false`, so if you didn't have set that environment variable the manual credits aren't going to be paid to sellers.

**Comment by leirwin** [comment]
Hi Javier -
My customer has the variable set to TRUE right now, and they are seeing that Hyperwallet is paying manual credits twice to sellers. The description of the variable in the documentation is sounding like the variable should be used when testing? 
_By default, the direct processing of manual credit notes is disabled. This can be enabled to facilitate manual testing of payout scenarios._
Based on the behavior they are seeing with double payments, it seems like the credit is being taken into account with Mirakl's automatic invoice, that's what I'm trying to validate.
We will do some testing in DEV on our side, but wanted to see if you had anymore thoughts on the behavior we're seeing.

Thanks!
Laura

**Comment by javierpoloe2y** [comment]
Hi @leirwin 

This comment in the documentation:

> By default, the direct processing of manual credit notes is disabled. This can be enabled to facilitate manual testing of payout scenarios.

refers to the fact, that manual credits are very useful during testing since you don't need to wait for the next billing cycle to generate an invoice for testing payments.

Regarding double payments, they should never happen. Payments are created in Hyperwallet using the Mirakl `invoice_id` field as the `clientPaymentId` in Hyperwallet so that Hyperwallet would reject any new payment request with the same `clientPaymentId`. In addition, the connector also checks if a payment already exists with the same `invoice_id` in Hyperwallet to prevent errors.

If you have more details about this double payment problem, please share them with us so we can investigate it further.

**Comment by javierpoloe2y** [comment]
Hi @leirwin,

Sorry, I didn't understand you at first, I think that you were saying that the same accounting document was being created two times in Hyperwallet.

As you said, manual credits are included in automatic invoices even when they are paid, so you should always put `PAYPAL_HYPERWALLET_OPERATOR_CREDIT_NOTES_ENABLED` to false (except for testing purposes). Of course, you could still create manual credit notes in Production and they will be paid in the next billing cycle.

We will update the documentation to make this clear.

**Comment by leirwin** [comment]
Hi Javier -
The root of the issue we're trying to solve is that Hyperwallet is paying sellers twice for manual credits that are created in Mirakl. 
PAYPAL_HYPERWALLET_OPERATOR_CREDIT_NOTES_ENABLED is set to TRUE in the HMC configuration.
So Hyperwallet is ingesting the manual credit document and paying sellers out for that amount. And then also paying sellers for the same credit AGAIN because the credit is included in the automatic invoice.
Yes, I think it would be good to update the documentation and make this more clear.

**Comment by javierpoloe2y** [comment]
Hi @leirwin 

We have published the connector documentation online so it's easy to accessing and navigate across it. You can find it here: [link](https://paypal.github.io/mirakl-hyperwallet-connector/)

Also in the section regarding the manual credits: [link](https://paypal.github.io/mirakl-hyperwallet-connector/component-hmc/4.15.0/payout/credit-notes.html#_manual_credit_notes), we have make it clear that it should be used only for testing purposes.
