### ISSUE TITLE
Please can you refactor the Mirakl Client so we can override configuration in one place?

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#79]
Hi Connector team,

We are hosting the connector in an AWS environment. The default implementation of the MiraklClient is to use Apache Http Client, however, we have found that in AWS, the default for http client is to use connection reuse.  The AWS load balancers drop idle connections after 300 seconds without sending an fin packet back to the connection initiator. 

To work around this, we implemented the configure method in MiraklMarketplacePlatformOperatorApiClientWrapperImpl

`	
@Override
	protected void configure(MiraklClientConfigWrapper clientConfigWrapper) {
		super.configure(clientConfigWrapper);

		log.info("Custom Configuration of HttpClient");

		// Leaving in commented as fallback option - No Connection Reuse
		clientConfigWrapper.getHttpClientBuilder().setConnectionReuseStrategy(NoConnectionReuseStrategy.INSTANCE);

		// Allow keep alive for 300 seconds (AWS NAT Gateway will kill connections after
		// 350 seconds)
		// clientConfigWrapper.getHttpClientBuilder().setKeepAliveStrategy((response,
		// context) -> 300000);
	}
`

However we found that there were places in the connector that also created 'new' instances of the class, so we took a blunt approach of replacing all occurences of :

final MiraklMarketplacePlatformOperatorApiClient miraklMarketplacePlatformOperatorApiClient,

with:

final MiraklMarketplacePlatformOperatorApiClientWrapperImpl miraklMarketplacePlatformOperatorApiClient,

This then causes a bit of a pain with updating our branch of code with every release as we get lots of conflicts with the class change.
Since we don't want to be in a place where our changes could cause issue with problem finding,
Please could you help in allowing clients to configure the connection reuse strategies?

Here's the list we modified:

 KYCMiraklApiConfig.java
MiraklSellerDocumentDownloadExtractServiceImpl.java
MiraklLetterOfAuthorizationBusinessStakeholderStrategy.java
MiraklProofOfAddressStrategy.java
MiraklProofOfBusinessStrategy.java
MiraklProofOfIdentityBusinessStakeholderStrategy.java
MiraklProofOfIdentityStrategy.java
AbstractMiraklSelectedDocumentsStrategy.java
KYCUserDocumentFlagIndividualStrategy.java
KYCUserDocumentFlagProofIdentityBusinessStakeHolderMockStrategy.java
KYCUserDocumentFlagProofIdentityBusinessStakeHolderStrategy.java
KYCUserDocumentFlagProofOfBusinessStrategy.java
AbstractUserDocumentFlagsStrategy.java
BusinessKYCUserLOAStatusNotificationStrategy.java
BusinessKYCUserStatusNotificationStrategy.java
IndividualKYCBusinessStakeholderStatusNotificationStrategy.java
IndividualKYCUserStatusNotificationStrategy.java
AbstractKYCUserStatusNotificationStrategy.java
KYCMiraklApiConfigTest.java
MiraklSellerDocumentDownloadExtractServiceImplTest.java
MiraklProofOfAddressStrategyTest.java
MiraklProofOfBusinessStrategyTest.java
MiraklProofOfIdentityBusinessStakeholderStrategyTest.java
MiraklProofOfIdentityStrategyTest.java
AbstractMiraklSelectedDocumentsStrategyTest.java
KYCUserDocumentFlagProofIdentityBusinessStakeHolderStrategyTest.java
AbstractUserDocumentFlagsStrategyTest.java
BusinessKYCUserLOAStatusNotificationStrategyTest.java
IndividualKYCBusinessStakeholderStatusExecutorNotificationStrategyTest.java
AbstractKYCUserStatusExecutorNotificationStrategyTest.java
ReportsMiraklApiConfig.java
ReportsMiraklExtractServiceImpl.java
ReportsMiraklApiConfigTest.java
ReportsMiraklExtractServiceImplTest.java
MiraklBankAccountExtractServiceImpl.java
SellersMiraklApiConfig.java
MiraklBusinessStakeholderExtractServiceImpl.java
TestingMiraklSellersExtractServiceImpl.java
MiraklBankAccountExtractServiceImplTest.java
SellersMiraklApiConfigTest.java
MiraklBusinessStakeholderExtractServiceImplTest.java
MiraklSellersExtractServiceImplCustomFieldsTest.java
MiraklSellersExtractServiceImplTest.java

Thanks and regards,
Russ

**Comment by RussGarratt** [comment]
https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html#nat-gateway-troubleshooting-timeout

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

We are already reviewing this, and in the next release, we will try to simplify the code so there is only one `MiraklMarketplacePlatformOperatorApiClient` bean. So if you want to change the implementation you would only need to change the bean definition in a `@Configuration` annotated class and it will apply to the whole connector.

**Comment by quim3ra** [comment]
Hi @RussGarratt,

New Release 4.16.0 has been released, we have centralized the creation of the `MiraklMarketplacePlatformOperatorApiClient` within the class `com.paypal.infrastructure.sdk.mirakl.impl.MiraklMarketplacePlatformOperatorApiClientWrapperImpl`.
