### ISSUE TITLE
[Question]: Can we run this app on kubernetes?

### ISSUE THREAD

**Issue by asishmishra** [paypal/mirakl-hyperwallet-connector#89]
We see build and boot:run needs tty, but can we back-ground these service during start-up.

**Comment by quim3ra** [comment]
Hi @asishmishra,

Yes, for sure, you can always use the orchestrator you want to deploy the application in the infrastructure of your choice.

**Comment by asishmishra** [comment]
In our case we need to automate the build and bootrun to be done in back group with out any manual intervention. yes .env file would be provided. Will this be achievable? in k8s we pass then as env variable in yaml file as sourcing .env is not working.

**Comment by quim3ra** [comment]
Hi @asishmishra ,

You can always try to setup a CD/CI environment to do automatically the process for you without manual intervention, anyway I suggest you discuss this matter with the infrastructure department of your company to see whether or not it is feasible.

Regards,
Carlos B.
