### ISSUE TITLE
[Issue]: How to process failed payments from HMC standpoints

### ISSUE THREAD

**Issue by siprapattanaik** [paypal/mirakl-hyperwallet-connector#91]
### Describe the Issue

We have  a monthly payout cycle .  We observed  that few of the invoices have failed as part of  09/15 payout because of Insufficient funds to cover the requested amount . However the funding amount was taken care by transferring the amount . Now the question is how do we process these failed payments. The status of the payment in Hyperwallet is in failed status and the screenshot is attached for reference . We did try invoking the invoice job manually . However there was no change to the invoice status in Hyperwallet . Could you please let us know how do we process these failed transactions .

![Invoice0915](https://user-images.githubusercontent.com/105679668/191112079-fae0f9a6-fbc1-4db3-bcc0-dedd8f7b1e01.PNG)
 

### Environment

Live/Production

### Version

4.13.1

**Comment by quim3ra** [comment]
Hi @siprapattanaik 

I don't quite understand correctly this part of the issue described `However the funding amount was taken care by transferring the amount`

To run failed payments, it would suffice calling the Invoice Job with a delta time with a date time earlier than the invoice creation.

```curl --location --request POST 'http://localhost:8080/job/invoices-extract?delta=earlier-date```

**Comment by siprapattanaik** [comment]
Hi @quim3ra,
                     Thanks for responding to my query . 

1. The invoices are still in PENDING state  in Mirakl . As  I mentioned earlier , we had manually triggered the job yesterday , but did not see anything getting processed .   The only difference between the regular invoice job vs the manual one which we triggered was the error of insufficient funds .We did not receive any error from the HMC when we invoked manually and the log is attached below from HMC. 
[LogSnapshotAfterInvJobrunmanually.txt](https://github.com/paypal/mirakl-hyperwallet-connector/files/9607848/LogSnapshotAfterInvJobrunmanually.txt)

At this point please let us know how to process the failed payments .Whether anything need to be done from HMC or Hyperwallet side.

**Comment by quim3ra** [comment]
Hi @siprapattanaik,

I suggest you contact HW team to know how to transition the payment with id `231275`.

Regards,
Carlos B.

**Comment by siprapattanaik** [comment]
Hi @quim3ra 
                  just FYI that the invoice 231275 was just one from the list . Do you recommend to work with Hyperwallet for the kind of issue we are having . Is there something that we can achieve from  HMC  standpoint ?

**Comment by max6001** [comment]
Hi @siprapattanaik 

Let me sum up the issue and explain a little on what's happening:
- Unfortunately you didn't have enough funds on your HW Escrow account to cover up for the payments which led several payments to fail.
- The connector is using the Mirakl invoice ID as unique ID when sending the payment request to HW.
- That unique ID is requested by HW to avoid duplicate payments.
- Once that unique ID has been used on a HW payment, it isn't possible to re-create a new payment with the same ID, reason why you can't reprocess the pending invoices.
- To our knowledge, the "failed" status in HW payment is a final stage which means you can't revert back that status to reproduce the payment.

We are going to develop the logic to handle failed HW payments and be able to properly reprocess them but it will take few weeks, maybe up to a month to have that new version available.

I'm afraid you will not be able to wait for that new release to reprocess those invoices and will have to reprocess them manually with the help of the HW team. Few things to keep in mind to help you in that process:
- You will need to reach out to HW to manually reprocess those payments.
- Be carefull, if you are taking an operator fee, the operator fee payment will also need to be covered.
- If HW manage to reprocess the payment keeping the same unique ID (currently attached to the failed payment), then the connector will automatically update the status of the invoice in Mirakl.
- If HW can't re-use the same unique ID and need to pass a new ID, it will have consequences:
-- The connector won't be able to update the invoice status in Mirakl, you will have to update those statuses manually.
-- The connector will generate several errors related to notification being received from HW related to invoices that don't exist in Mirakl. Simply disregard those errors.
-- If you are ever using HW reportings for reconciliation, those manually reprocessed payments will have a unique ID that will differ from the Mirakl invoice ID and could create confusion for your accounting teams.

We apologize for the inconvenience and remain available if needed.

In the future, please make sure to keep enough money on the Escrow account to cover up for the payment of your sellers.

Best;

**Comment by quim3ra** [comment]
Hi @siprapattanaik,

We have deployed the new release with an improvement to tackle this behaviour. https://github.com/paypal/mirakl-hyperwallet-connector/releases/tag/4.17.0

**Comment by andrea-simontacchi** [comment]
Hi!
does this update take in consideration also payments with returned or expired status?

Cheers
