### ISSUE TITLE
Build failed while doing local setup for hyperwallet connector 

### ISSUE THREAD

**Issue by Msolia1** [paypal/mirakl-hyperwallet-connector#94]
Hi , 
I followed the same steps. When i try to perform the gradlew build in my local. Build failed and facing the error's in below mentioned test classes. 
HyperwalletLoggingErrorsUtilTest.java 
AbstractHmcFileServiceTest.java
HMCFileServiceImplTest.java
HMCFileServiceMockImplTest.java
BusinessStakeHolderModelTest.java
SellerModelTest.java

The following attachment is refernce for HyperwalletLoggingErrorsUtilTest.java : 
![HMC_Build](https://user-images.githubusercontent.com/114494101/192537629-153955c7-d062-4c94-aba6-65ef70902d19.png)
![HMC_Build_2](https://user-images.githubusercontent.com/114494101/192538194-3a95263f-c6b5-4df3-8141-a0c6a4626e91.png)
![HMC_Build_3](https://user-images.githubusercontent.com/114494101/192538208-a2da2d03-fe00-4546-bf68-81cf7ee25c1a.png)

**Comment by quim3ra** [comment]
Hi @Msolia1,

What's the JDK version and the HMC version you're having problems to compile?

Regards,
Carlos B.

**Comment by Msolia1** [comment]
Hi @quim3ra,

We are using jdk-15.0.2 and HMC 4.16.0

Thanks,
Madhav

**Comment by quim3ra** [comment]
Can you ensure all files within the repository you cloned are encoded with UF-8?

**Comment by Msolia1** [comment]
![image](https://user-images.githubusercontent.com/114497129/193003800-869d9bd3-bda7-4ec1-ab1f-486b9bfb345e.png)

Yes, I have checked all files are encoded with UTF-8

We have unzip using 7zip application in Windows OS.

**Comment by quim3ra** [comment]
Hi, the connector is not currently supporting Windows as SO, we suggest you use a Linux machine.
