### ISSUE TITLE
[Question]: Need information on Database usage 

### ISSUE THREAD

**Issue by Msolia1** [paypal/mirakl-hyperwallet-connector#95]
Hi,

We have seen in connector code base that it's using HSQL for few modules.

What is use of DB in connector and up to what size it can go?

This will help us to know on environment setup for connector for Production.

Thanks,
Madhav

**Comment by saitohfin** [comment]
Not there are any specific set for that, therefore, I guess we are using the default configuration which we can find in his page.

http://hsqldb.org/web/hsqlFAQ.html

What is the biggest known HSQLDB database?
The current default size limit of an HSQLDB database is 8TB for all CACHED tables combined (this can be extended to 256TB with a connection property). The size limit for each TEXT table is 256GB. In addition, maximum total lob size is 64TB. If you use large MEMORY tables, memory is only limited by the allocated JVM memory, which can be several GB on modern machines and 64bit operating systems. We have performed extensive tests with the latest versions using the TestCacheSize and other test programs inserting millions of rows and resulting in data files of up to 16 GB and larger LOB sizes. Users have reported the use of databases with up to 900 million rows.
